### ISSUE TITLE
Projects > Text content 

### ISSUE THREAD

**Issue by MaxcoSteph** [MaxcoSteph/h-e#2]
Push all text content down so it no longer sits upon the image for greater legibility. H&E understand that this will push text below the fold and are ok with his... hoping the project title will be at bottom of fold so people know to scroll down for more

**Comment by lawrymaxco** [comment]
I think this is working the way they want now

**Comment by MaxcoSteph** [comment]
When I check this the title (and everything on this line) is still over image?
