### ISSUE TITLE
Projects > Gradient issue on desktop

### ISSUE THREAD

**Issue by MaxcoSteph** [MaxcoSteph/h-e#3]
The gradient is currently displaying on all 4 sides of the image in projects  - see screenshot attached... Needs to look as it does on homepage so top and bottom only

Note - displaying fine on mobile 

![screen shot 2016-07-15 at 1 00 10 pm](https://cloud.githubusercontent.com/assets/19701943/16862366/37a44dcc-4a8c-11e6-83d8-34d6cc991e68.png)

**Comment by lawrymaxco** [comment]
This is also fixed

**Comment by MaxcoSteph** [comment]
Perfect
