### ISSUE TITLE
Projects > Gradient Mobile

### ISSUE THREAD

**Issue by MaxcoSteph** [MaxcoSteph/h-e#4]
Can we please increase the height of slideshow imagery on project pages so it mimics what we have working successfully on homepage? H&E understand this will result in further cropping of image but want it to be uniform across the two sections of site

**Comment by lawrymaxco** [comment]
OK - after some testing I think this is working correctly?

**Comment by MaxcoSteph** [comment]
When I check this and I've also noticed on desktop the hard edge of photo is showing - is this due tot he gradient being moved down?
